### PR TITLE
tests 2nd iteration

### PR DESCRIPTION
**Pull request by mattiaerre**
# Description

- more eslinting

- move on headers listener function into a separate component

- add tests

- move socket.io init into a separate component

- make sure node v4 is also supported

## Coverage summary

```
Statements   : 88.31% ( 68/77 )
Branches     : 81.58% ( 31/38 )
Functions    : 100% ( 0/0 )
Lines        : 93.15% ( 68/73 )
```

### CODE REVIEW

**Comment by mattiaerre** [comment]
hi @RafalWilinski as per my Todo I will tackle next socket.io stuff and node v4. Meanwhile, if you would like to start having a look at this PR that would be really appreciated. If you are able to think about adding more tests as well as other scenarios I think that this woul be really beneficial.
Thanks!

**Comment by mattiaerre** [comment]
hi @RafalWilinski I extracted also socket io init into a separate component; also now node v4 should work as expected. If you happy to merge and republish then we can let @starsoccer know that it is possible to run the middleware also on node v4.
thanks,

**Comment by RafalWilinski** [comment]
Again, great work @mattiaerre and big thanks for that!

**Comment by RafalWilinski** [comment]
Version `0.1.2` has landed on NPM.

**Comment by mattiaerre** [comment]
my pleasure @RafalWilinski happy you liked it; I am going to send you an email w/ a bunch of ideas I've got in order to decide what to do next 😉

**Comment by starsoccer** [comment]
Database monitoring would be nice, but that might be out of the scope for an express status monitor.

**Comment by mattiaerre** [comment]
hi @starsoccer yes indeed database monitoring would be a really cool feature. databases are always a problem, aren't they? but like you suggested I think that this is definitely out of scope for this particular middleware; everything and especially middlewares should follow the SRP principle. so, what about creating one yourself and publish it as another open source project? that'd be cool! (my 2 cents obviously)

**Comment by starsoccer** [comment]
Agreed, I will for sure look into it. Not sure if databases are always the problem, could be the people managing the databases ;)

Back on scope though, I would say making the monitor more user expandable/customizable could be a neat idea.

**Comment by solognt** [comment]
Node 4 works again thanx!

**Comment by mattiaerre** [comment]
thanks for your feedback @solognt

**Comment by mattiaerre** [comment]
very good point @starsoccer you are definitely right re databases/ppl 😅 
nice one re the customizability of the monitor 👍

**Pull request merged**
