### PR TITLE
HTTP basic auth

### PR DESCRIPTION
**Pull request by n1try**
Fixed config checks and added basic HTTP auth to optionally secure the status page, as requested in #26.

### CODE REVIEW

**Comment by RafalWilinski** [comment]
@n1try - First of all, thank you for you engagement and this PR, I'm glad there are people who want to contribute. 
However, I cannot merge this PR because of two flaws:

1. `basic-auth` module is not added to `package.json` file. Please add it.
2. If authentication is required, then it's required on ALL routes, not only on `/status` route. Please move ` if (config.auth)` part inside `if (req.path === config.path)` block.

Thanks

**Comment by n1try** [comment]
Thank you, obviously I was a bit hasty pushing this.
I'm not sure, but wouldn't have the socket connection to be established only if there was a successful authentication, too? So would not only the authentication check be needed to be moved inside `if (req.path === config.path)`, but also the socket initialization section (right below the auth check)?

**Comment by RafalWilinski** [comment]
I don't think that socket initialisation should be moved here. 

Actually, I doesn't matter because sooner or later admin would access `/status` page and start socket.io but just lets try not to increase cyclomatic complexity by nesting another `if`.

**Comment by RafalWilinski** [comment]
@n1try Please update with master branch and I'll merge it. Right now, I'm unable to do that.

**Pull request merged**
