### PR TITLE
socket-io-init: accept 'config.authorize' function

### LINKED ISSUE #66: Socket connections are not authenticated
While mounting at a path (barring #63) allows for authenticating the user *HTML page* the socket connection appears to be unauthenticated.  

Looking at [this article](http://www.scotthasbrouck.com/blog/2016/3/18/passportjs-express-session-with-sockeio) it is not difficult to authenticate socket.io sessions.  The first part (`io.use(...)`) looks like it can be done by the user and the io instance passed in the `config` arg down to `socketIoInit`.

However the second part (checking the `socket.request.user` on `connect`) still needs to happen.  This could be doable by taking a user-defined callback which you would call inside the `connect` handler, which should `return true` if the connection is authorized.

### PR DESCRIPTION
**Pull request by thom-nic**
To auth socket.io connections.  Function should take a single argument,
which is the socket instance of the new connection.  It should
return a promise that resolves with a boolean value indicating whether
the connection is authorized.  If the promise resolves with a `false`
result or rejects, the socket is disconnected.

Fixes #66

### CODE REVIEW

**Comment by thom-nic** [comment]
No doc or test yet but wanted to push something up for review.

**Comment by thom-nic** [comment]
@RafalWilinski LMK if this looks good and I'll write up some tests.

**Comment by RafalWilinski** [comment]
I would love to have that merged already but tests hang, debugging...

**Comment by thom-nic** [comment]
Thanks!  Do you have a target date for a next release?  No rush just trying to get a ballpark of when I should update my dependencies.

**Comment by RafalWilinski** [comment]
Version `0.1.7` is already live on npm and GitHub releases.

**Comment by thom-nic** [comment]
Fantastic!  Thanks.

**Pull request merged**
